### PR TITLE
Websafe

### PR DESCRIPTION
**Pull request by rikkertkoppes**
I added the widths for all websafe fonts:

- Andale Mono
- Arial
- Comic Sans MS
- Courier New
- Georgia
- Impact
- Times New Roman
- Trebuchet MS
- Verdana
- Webdings

Also made some small changes along the way to make the process easier.

### CODE REVIEW

**Comment by rikkertkoppes** [comment]
How do you feel about the es-lint errors in widthsMap? I would say it is far easier to maintain it in json format.

**Comment by adambisek** [comment]
Thanks you for your PR. It's really great! :)

I would note only thing before merge - about widthsMap: Why do you think that json is better than js file? I can't see any advantage at this moment. By the way, now it is JSON in JS file (with supressed warnings due to JSON style) and for me it would feel better if it would be regular JS.

**Comment by rikkertkoppes** [comment]
I'd say this way it is easier to copy-paste from the results of pixelWidthCalculator.html. That is basically all.

One thing I thought of is to save it all as a json file and require it directly as json. However, that would make the lib unsuitable for easy browser usage.

**Comment by adambisek** [comment]
Yes, that makes sense. I have no problem with that at this time.

All stuff goes through compilation, so browser support would not be a serious problem, but let's leave it as JS file.

**Comment by adambisek** [comment]
Published version 1.1.1 into npm.
Thanks for your PR 👍

**Pull request merged**
