### PR TITLE
added avenir font

### PR DESCRIPTION
**Pull request by S-Cardenas**
Added avenir font to width maps.

### CODE REVIEW

**Comment by adambisek** [comment]
Hi, I welcome your contribution, but I can see that some of current fonts changed their widths too. What is the cause? This can cause huge back-compatibility break other users.

**Comment by S-Cardenas** [comment]
It's weird that the other fonts changed. I followed your instructions as per the documentation and copied and pasted the entire output that was shown on the browser. Should I only be copying and pasting the `avenir` part of the output?

**Comment by S-Cardenas** [comment]
@adambisek I updated the pull request so as not interfere with the previous fonts. Could you please review and let me know?

I need this for a project that my company is pushing into production soon so all help is greatly appreciated 👍

**Comment by adambisek** [comment]
Looks good :)

**Comment by S-Cardenas** [comment]
Thanks!!

**Pull request merged**
